# Copyright (c) 2024, Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

name: Documentation

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        doxygen-version: [1.9.6, 1.14.0]
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          DOXYGEN_VERSION="${{ matrix.doxygen-version }}"
          wget --no-verbose "https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz"
          tar xf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          echo "${PWD}/doxygen-${DOXYGEN_VERSION}/bin" >> $GITHUB_PATH
          pip install -r doc/requirements.txt

      - name: Build
        run: |
          cd doc
          doxygen

          SPHINXOPTS="-W" make html

          mkdir deploy
          mv _build_doxygen/html deploy/doxygen
          mv _build_sphinx/html/* deploy

      - name: Setup pages
        if: github.event_name != 'pull_request' && matrix.doxygen-version == '1.14.0'
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Upload pages artifact
        if: github.event_name != 'pull_request' && matrix.doxygen-version == '1.14.0'
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: doc/deploy

      - name: Upload artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: docs-doxygen-${{ matrix.doxygen-version }}
          path: doc/deploy

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: build
    if: github.event_name != 'pull_request'
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
